language: node_js
node_js:
  - "node"
  - "iojs"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"

env:
  - THE_SCRIPT=install
  - THE_SCRIPT="install ./local_module/sub_project"
  - THE_SCRIPT=pack
  - THE_SCRIPT=publish

script: 
  - npm ${THE_SCRIPT}
