language: node_js
node_js:
  - "node"
  - "iojs"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"

env:
  - THE_SCRIPT=install
  - THE_SCRIPT="install ./local_module/sub_project"
  - THE_SCRIPT=publish
  - THE_SCRIPT=pack

script: 
  - npm ${THE_SCRIPT}
